import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ModeToggle } from "@/components/mode-toggle";
import { Navbar } from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Separator } from "@/components/ui/separator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dante Sparrås",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="sticky top-0 z-50 flex h-12 max-w-screen items-center justify-end overflow-x-hidden mx-auto px-2 pt-2 gap-2 sm:gap-4 md:max-w-3xl transition-shadow duration-300 after:z-1 after:transition-[background-color]">
            <Navbar />
            <Separator orientation="vertical" className="h-4 my-auto" />
            <ModeToggle />
          </header>
          <main>{children}</main>
          <footer></footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
